#! /bin/bash

sudo cp -r ~/.vimrc ~/.zshrc ~/.xinitrc ~/.Xauthority ~/.Xresources ~/bob_dotfiles
sudo cp -r ~/.config/alacritty ~/.config/i3 ~/.config/rofi ~/.config/polybar ~/bob_dotfiles
./automatedGit
